my:
  greeting: Helloworld
  list: 
    values: One, Two, Three


db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_database_name
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

