my:
  greeting: Helloworld neww4
  list: 
    values: One, Two, Three


db:
  connection: connection-string-here
  host: 127.0.0.1
  port: 1200
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ineuron1
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

